# Dependabot takes the effort out of maintaining your dependencies. You can use
# it to ensure that your repository automatically stays updated with latest
# releases of the packages and applications it depends on. Update the list of
# package ecosystems below as needed for your repo.

# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem

version: 2
updates:
  # - package-ecosystem: "devcontainers"
  #   directory: /
  #   schedule:
  #     interval: "weekly"
  #   cooldown:
  #     default-days: 7

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  # - package-ecosystem: "gomod"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   cooldown:
  #     default-days: 7
