# prod sealed secrets. Secrets are generated via `bin/create-secret`
secrets:
  sources:
    sealedSecrets:
      items: [] # remove the [] when adding an entry by hand
        # - name: my-secret
        #   ciphertext: AgB1a2...
        #   envVar: MY_SECRET
        #   mountPath: /secrets/mine
